import {
  ElConfigProvider,
  ElButton,
  ElDatePicker,
  ElEmpty,
  ElHeader,
  ElContainer,
  ElMain,
  ElAside,
  ElFooter,
  ElLoading,
  ElMenu,
  ElSubMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElImage,
  ElPopover,
  ElTooltip,
  ElCard,
  ElForm,
  ElFormItem,
  ElInput,
  ElRadio,
  ElRadioGroup,
  ElDialog,
  ElSelect,
  ElOption,
  ElUpload,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElRow,
  ElCol,
  ElTable,
  ElTableColumn,
  ElPagination,
  ElTree,
  ElAvatar,
  ElIcon
} from 'element-plus';

const components = [
  ElConfigProvider,
  ElButton,
  ElDatePicker,
  ElEmpty,
  ElHeader,
  ElContainer,
  ElMain,
  ElAside,
  ElFooter,
  ElMenu,
  ElSubMenu,
  ElMenuItem,
  ElMenuItemGroup,
  ElImage,
  ElPopover,
  ElTooltip,
  ElCard,
  ElForm,
  ElFormItem,
  ElInput,
  ElRadio,
  ElRadioGroup,
  ElDialog,
  ElSelect,
  ElOption,
  ElUpload,
  ElRow,
  ElCol,
  ElTable,
  ElTableColumn,
  ElPagination,
  ElBreadcrumb,
  ElBreadcrumbItem,
  ElTree,
  ElAvatar,
  ElIcon
];

const plugins = [ElLoading];

import { Edit, Lock, Platform, Plus, Refresh, Search, SwitchButton, User } from '@element-plus/icons';

const icons = [Edit, Platform, SwitchButton, Lock, User, Search, Refresh, Plus];

export { components, plugins, icons };
